version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

build:
  os: ubuntu-24.04
  tools:
    python: mambaforge-latest

conda:
  environment: docs/rtd_environment.yaml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
