line-length = 100
exclude = [
  "docs",
  ".tox",
  ".eggs",
  "build",
]

[lint]
select = [
  "C4",  # flake8-comprehensions
  "E",  # pycodestyle
  "W",  # pycodestyle
  "F",  # Pyflakes
  "UP",  # pyupgrade
  "RUF",  # Ruff-specific rules
]
extend-select = [
  "COM",  # flake8-commas
]
ignore = [
  # pycodestyle (E, W)
  "E501",  # line-too-long
  "E721",  # type-comparison
  "E731",  # lambda-assignment

  # Pyflakes (F)
  "F841",  # unused-variable

  # Ruff-specific rules (RUF)
  "RUF001",  # ambiguous-unicode-character-string
  "RUF002",  # ambiguous-unicode-character-docstring
  "RUF005",  # Consider `(*result, data)` instead of concatenation
  "RUF010",  # use conversion in f-string
  "RUF012",  # Mutable class attributes should be annotated with `typing.ClassVar`

  # flake8-commas (COM)
  "COM812",  # TrailingCommaMissing
]
unfixable = [
  "E711"  # NoneComparison. Hard to fix b/c numpy has it's own None.
]

[lint.extend-per-file-ignores]
"setup.py" = [
  "INP001",  # Part of configuration, not a package.
  "ICN001",
  "UP018"
]
"test_*.py" = [
  "B018",  # UselessExpression
  "D",  # pydocstyle
  "PGH001",  # No builtin eval() allowed
  "S101",  # Use of assert detected
]
".pyinstaller/*.py" = ["INP001"]  # Not a package.
"conftest.py" = ["INP001"]  # Part of configuration, not a package.
"docs/*.py" = [
  "INP001",  # implicit-namespace-package. The examples are not a package.
]
"examples/*.py" = [
  "E402",  # Imports are done as needed.
  "INP001",  # implicit-namespace-package. The examples are not a package.
  "T203"  # pprint found
]

[lint.flake8-annotations]
ignore-fully-untyped = true
mypy-init-return = true

[lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[lint.flake8-type-checking]
exempt-modules = []

[lint.isort]
known-first-party = ["astropy", "extension_helpers"]

[lint.pydocstyle]
convention = "numpy"
