dist: xenial
language: python
python: 3.8.5

jobs:
  # Don't wait for allowed failures
  fast_finish: true
  include:
    - name: Latest dependencies

    - name: Old dependencies
      python: 3.6.10
      install:
        - pip install numpy~=1.16.0
        - pip install -e .[test]

    - name: Dev dependencies
      install:
        - pip install git+https://github.com/numpy/numpy
        - pip install git+https://github.com/astropy/astropy
        - pip install -e .[test]
      addons:
        apt:
          packages:
            - libopenblas-base
            - libopenblas-dev

    - name: Documentation build
      install:
        - pip install -e .[test,docs]
      script:
        - sphinx-build docs docs/_build
      addons:
        apt:
          packages:
            - libopenblas-base
            - libopenblas-dev

    - name: Code style
      install:
        - pip install flake8
      script:
        - flake8 --count

install:
  - pip install -e .[test]

script:
  - pytest
