dist: xenial
language: python
python: 3.8.5

jobs:
  # Don't wait for allowed failures
  fast_finish: true
  include:
    - name: Latest dependencies

    - name: Old dependencies
      python: 3.6.10
      install:
        - pip install numpy~=1.16.0
        - pip install -e .[test]

    - name: Dev dependencies
      install:
        # Install a nightly wheel of numpy from the anaconda folks
        - pip install -i https://pypi.anaconda.org/scipy-wheels-nightly/simple --pre -I numpy
        - pip install git+https://github.com/astropy/astropy
        - pip install -e .[test]

    - name: Documentation build
      install:
        - pip install -e .[docs]
      before_script:
        - cd docs
      script:
        - sphinx-build . ./_build
      addons:
        apt:
          packages:
            - texlive-latex-extra
            - dvipng
            - graphviz

    - name: Code style
      install:
        - pip install flake8
      script:
        - flake8 --count

install:
  - pip install -e .[test]

script:
  - pytest
