# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

compiler: gcc

# Cache can be cleared from the travis settings menu, see docs currently at
# https://docs.travis-ci.com/user/caching#Clearing-Caches
cache:
  - ccache

os:
    - linux

stage: Comprehensive tests

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - language-pack-de

env:
    global:
        # Set defaults to avoid repeating in most cases
        - PYTHON_VERSION=3.6
        - NUMPY_VERSION=stable
        - MAIN_CMD='python setup.py'
        - CONDA_DEPENDENCIES='Cython'
        - CONDA_ALL_DEPENDENCIES='astropy Cython'
        - SETUP_XVFB=True
        - EVENT_TYPE='push pull_request'
        - SETUP_CMD='test'

        # PEP8 errors/warnings:
        # E101 - mix of tabs and spaces
        # W191 - use of tabs
        # W291 - trailing whitespace
        # W292 - no newline at end of file
        # W293 - trailing whitespace
        # W391 - blank line at end of file
        # E111 - 4 spaces per indentation level
        # E112 - 4 spaces per indentation level
        # E113 - 4 spaces per indentation level
        # E502 - the backslash is redundant between brackets
        # E722 - do not use bare except
        # E901 - SyntaxError or IndentationError
        # E902 - IOError
        - FLAKE8_OPT="--select=E101,W191,W291,W292,W293,W391,E111,E112,E113,E502,E722,E901,E902"

stages:
   # Do the style check and a single test job, don't proceed if it fails
   - name: Initial tests
   # Do the rest of the tests
   - name: Comprehensive tests
   - name: Cron tests
     if: type = cron

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:

        - stage: Initial tests
          env: PYTHON_VERSION=3.6 SETUP_CMD='egg_info'

        - stage: Initial tests
          env: PYTHON_VERSION=3.7 SETUP_CMD='egg_info'

        # Try MacOS X.
        - os: osx
          stage: Cron tests
          env: MAIN_CMD='pytest' SETUP_CMD=''
               CONDA_DEPENDENCIES=$CONDA_ALL_DEPENDENCIES
               PIP_DEPENDENCIES='' EVENT_TYPE='cron'

        # Check for sphinx doc build warnings - we do this first because it
        # runs for a long time. The sphinx build also has some additional
        # dependencies. Using a more stringent locale than UTF-8.
        - os: linux
          env: SETUP_CMD='build_docs -w'
               CONDA_DEPENDENCIES=$CONDA_ALL_DEPENDENCIES
               PIP_DEPENDENCIES='sphinx sphinx-astropy sphinx-automodapi'
               LC_CTYPE=C LC_ALL=C LANG=C

        # TODO: Add doctest back using pytest-doctestplus?
        #
        # Try all python versions and Numpy versions. Since we can assume that
        # the Numpy developers have taken care of testing Numpy with different
        # versions of Python, we can vary Python and Numpy versions at the same
        # time. Since we test the latest Numpy as part of the builds with all
        # optional dependencies below, we can focus on older builds here.
        - os: linux
          env: PYTHON_VERSION=3.6
               NUMPY_VERSION=1.15
               OPENMP_EXPECTED=False
               INSTALL_CMD='python setup.py build_ext --inplace'
               CONDA_DEPENDENCIES=$CONDA_ALL_DEPENDENCIES
               PIP_DEPENDENCIES='sphinx pytest-openfiles'
               TEST_CMD='pytest --open-files'
          script:
            - $INSTALL_CMD
            - $TEST_CMD

        # Now try with all optional dependencies.
        - os: linux
          env: PYTHON_VERSION=3.7
               NUMPY_VERSION=1.16
               MAIN_CMD='pytest' SETUP_CMD=''
               CONDA_DEPENDENCIES=$CONDA_ALL_DEPENDENCIES
               PIP_DEPENDENCIES="jplephem asdf"
               LC_CTYPE=C.ascii LC_ALL=C

        - os: linux
          stage: Initial tests
          env: CONDA_DEPENDENCIES=$CONDA_ALL_DEPENDENCIES
               PYTEST_VERSION='>3.2'
               MAIN_CMD='pytest --durations=50' SETUP_CMD=''
          compiler: clang

        - os: linux
          env: MAIN_CMD='pytest --cov' SETUP_CMD=''
               CONDA_DEPENDENCIES=$CONDA_ALL_DEPENDENCIES
               PIP_DEPENDENCIES=""
               LC_CTYPE=C.ascii LC_ALL=C
               CFLAGS='-ftest-coverage -fprofile-arcs -fno-inline-functions -O0'
               NUMPY_VERSION=1.16
               EVENT_TYPE='push pull_request cron'

        # Try pre-release version of Numpy without optional dependencies
        - os: linux
          env: NUMPY_VERSION=prerelease
               EVENT_TYPE='push pull_request cron'
               MAIN_CMD='pytest' SETUP_CMD=''

        # Try older numpy versions
        - os: linux
          env: NUMPY_VERSION=1.13
               CONDA_DEPENDENCIES=$CONDA_ALL_DEPENDENCIES
               MAIN_CMD='pytest' SETUP_CMD=''
               EVENT_TYPE='push pull_request cron'

        # Do a PEP8/pyflakes test with flake8
        - os: linux
          stage: Initial tests
          env: MAIN_CMD="flake8 drizzle --count $FLAKE8_OPT" SETUP_CMD=''

        # We check numpy-dev also in a job that only runs from cron, so that
        # we can spot issues sooner. We do not use remote data here, since
        # that gives too many false positives due to URL timeouts.
        - os: linux
          stage: Cron tests
          env: NUMPY_VERSION=dev
               EVENT_TYPE='cron'
               CONDA_DEPENDENCIES=$CONDA_ALL_DEPENDENCIES
               MAIN_CMD='pytest' SETUP_CMD=''


install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
    - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == *--coverage* ]]; then
        if [ "$TRAVIS_REPO_SLUG" = "astropy/astropy" -o "$TRAVIS_PULL_REQUEST_SLUG" = "astropy/astropy" ]; then
          cpp-coveralls -E ".*convolution.*" -E ".*_erfa.*" -E ".*\.l" -E ".*\.y" -E ".*flexed.*" -E ".*cextern.*" -E ".*_np_utils.*" -E ".*cparser.*" -E ".*cython_impl.*" --dump c-coveralls.json;
          coveralls --merge=c-coveralls.json --rcfile='astropy/tests/coveragerc';
        fi;
      fi
