name: build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/publish.yml
    with:
      upload_to_pypi: false
      targets: |
        # Linux wheels
        - cp3*-manylinux_x86_64
        # MacOS wheels
        - cp3*-macosx_x86_64
        # Until we have arm64 runners, we can't automatically test arm64 wheels
        - cp3*-macosx_arm64
        # Windows wheels
        - cp3*-win32
        - cp3*-win_amd64
      sdist: true
      test_command: python -c "from drizzle import cdrizzle"
